### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: './results/models/MEND/gpt2-xl'

### ISSUE THREAD

**Issue by lunyu-half** [zjunlp/EasyEdit#340]
When I ran the code as follows:

``` python
## In this case, we use MEND method, so you should import `MENDHyperParams`
from easyeditor import BaseEditor, MENDHyperParams

## Loading config from hparams/MEMIT/gpt2-xl.yaml
hparams = MENDHyperParams.from_hparams('./hparams/MEND/gpt2-xl')


## edit descriptor: prompt that you want to edit
prompts = [
    'What university did Watts Humphrey attend?',
    'Which family does Ramalinaceae belong to',
    'What role does Denny Herzig play in football?'
]
## You can set `ground_truth` to None !!!(or set to original output)
ground_truth = ['Illinois Institute of Technology', 'Lecanorales', 'defender']
## edit target: expected output
target_new = ['University of Michigan', 'Lamiinae', 'winger']

## Construct Language Model Editor
editor = BaseEditor.from_hparams(hparams)

locality_inputs = {
    'neighborhood':{
        'prompt': ['Joseph Fischhof, the', 'Larry Bird is a professional', 'In Forssa, they understand'],
        'ground_truth': ['piano', 'basketball', 'Finnish']
    },
    'distracting': {
        'prompt': ['Ray Charles, the violin Hauschka plays the instrument', 'Grant Hill is a professional soccer Magic Johnson is a professional', 'The law in Ikaalinen declares the language Swedish In Loviisa, the language spoken is'],
        'ground_truth': ['piano', 'basketball', 'Finnish']
    }
}

metrics, edited_model, _ = editor.edit(
    prompts=prompts,
    ground_truth=ground_truth,
    target_new=target_new,
    locality_inputs=locality_inputs,
    sequential_edit=False # True: start continuous editing ✈️
)
## metrics: edit success, rephrase success, locality e.g.
## edited_model: post-edit model
```

I encountered the problem below:

``` bash
2024-07-20 11:39:21,845 - easyeditor.editors.editor - INFO - Instantiating model
2024-07-20 11:39:21,845 - easyeditor.editors.editor - INFO - Instantiating model
2024-07-20 11:39:21,845 - easyeditor.editors.editor - INFO - Instantiating model
2024-07-20 11:39:21,845 - easyeditor.editors.editor - INFO - Instantiating model
07/20/2024 11:39:21 - INFO - easyeditor.editors.editor -   Instantiating model
2024-07-20 11:39:23,928 - easyeditor.editors.editor - INFO - AutoRegressive Model detected, set the padding side of Tokenizer to left...
2024-07-20 11:39:23,928 - easyeditor.editors.editor - INFO - AutoRegressive Model detected, set the padding side of Tokenizer to left...
2024-07-20 11:39:23,928 - easyeditor.editors.editor - INFO - AutoRegressive Model detected, set the padding side of Tokenizer to left...
2024-07-20 11:39:23,928 - easyeditor.editors.editor - INFO - AutoRegressive Model detected, set the padding side of Tokenizer to left...
07/20/2024 11:39:23 - INFO - easyeditor.editors.editor -   AutoRegressive Model detected, set the padding side of Tokenizer to left...
100%|██████████| 3/3 [00:07<00:00,  2.59s/it]
  0%|          | 0/3 [00:00<?, ?it/s]07/20/2024 11:39:39 - INFO - easyeditor.trainer.algs.MEND -   Hooked 6 modules
07/20/2024 11:39:39 - INFO - easyeditor.trainer.algs.MEND -   Building Gradient Transform with MLP class <class 'easyeditor.trainer.algs.local_nn.IDMLP'>
07/20/2024 11:39:39 - INFO - easyeditor.trainer.algs.local_nn -   Building IDMLP (id) [8000, 8000, 8000]
07/20/2024 11:39:40 - INFO - easyeditor.trainer.algs.MEND -   Building Gradient Transform with MLP class <class 'easyeditor.trainer.algs.local_nn.IDMLP'>
07/20/2024 11:39:40 - INFO - easyeditor.trainer.algs.local_nn -   Building IDMLP (id) [8000, 8000, 8000]
  0%|          | 0/3 [00:00<?, ?it/s]
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In[2], line 33
     20 editor = BaseEditor.from_hparams(hparams)
     22 locality_inputs = {
     23     'neighborhood':{
     24         'prompt': ['Joseph Fischhof, the', 'Larry Bird is a professional', 'In Forssa, they understand'],
   (...)
     30     }
     31 }
---> 33 metrics, edited_model, _ = editor.edit(
     34     prompts=prompts,
     35     ground_truth=ground_truth,
     36     target_new=target_new,
     37     locality_inputs=locality_inputs,
     38     sequential_edit=False # True: start continuous editing ✈️
     39 )

File e:\AIProjects\sources\EasyEdit\easyeditor\editors\editor.py:160, in BaseEditor.edit(self, prompts, target_new, ground_truth, rephrase_prompts, locality_inputs, portability_inputs, sequential_edit, verbose, **kwargs)
    157 else:
    158     requests = _prepare_requests(prompts, target_new, ground_truth, rephrase_prompts, locality_inputs, portability_inputs, **kwargs)
--> 160 return self.edit_requests(requests, sequential_edit, verbose, test_generation=test_generation, **kwargs)

File e:\AIProjects\sources\EasyEdit\easyeditor\editors\editor.py:334, in BaseEditor.edit_requests(self, requests, sequential_edit, verbose, test_generation, **kwargs)
    332 else:
    333     for i, request in enumerate(tqdm(requests, total=len(requests))):
--> 334         edited_model, weights_copy, icl_examples = edit_func(request)
    335         edit_evaluation(all_metrics, request, edited_model, i, eval_metric, test_generation, icl_examples, **kwargs)
    336         if self.alg_name == 'KN' or self.alg_name == 'GRACE' or self.alg_name == 'WISE':

File e:\AIProjects\sources\EasyEdit\easyeditor\editors\editor.py:287, in BaseEditor.edit_requests.<locals>.edit_func(request)
    276     edited_model, weights_copy, icl_examples = self.model, {}, self.apply_algo(
    277         self.model,
    278         self.tok,
   (...)
    284         train_ds=kwargs['train_ds'] if self.alg_name == 'IKE' else None
    285     )
    286 else:
--> 287     edited_model, weights_copy = self.apply_algo(
    288         self.model,
    289         self.tok,
    290         [request],
    291         self.hparams,
    292         copy=False,
    293         return_orig_weights=True,
    294         keep_original_weight=False,
    295         train_ds=kwargs['train_ds'] if self.alg_name == 'IKE' else None
    296     )
    297     icl_examples = None
    298 return edited_model, weights_copy, icl_examples

File e:\AIProjects\sources\EasyEdit\easyeditor\models\mend\mend_main.py:81, in MendRewriteExecutor.apply_to_model(self, model, tok, requests, hparams, copy, return_orig_weights, keep_original_weight, **kwargs)
     69 """
     70 Given a request, for example
     71 {'prompt': '{} has the position of',
   (...)
     77 how mend will change the weights of the model.
     78 """
     80 if not self.is_init:
---> 81     self.init_model(model, tok, hparams)
     83 weights_copy = {}
     84 model = deepcopy(self.model) if copy else self.model

File e:\AIProjects\sources\EasyEdit\easyeditor\models\mend\mend_main.py:38, in MendRewriteExecutor.init_model(self, model, tok, params)
     34 # add_padding(self.tokenizer, self.model)
     35 
     36 # Load the trained MEND model
     37 self.alg = MEND(self.model, params, lambda: deepcopy(self.model))
---> 38 d = torch.load(params.archive, map_location='cpu')
     40 self.alg.load_state_dict(
     41     {k.replace("gtn.", "mend."): v for k, v in d["model"].items()}
     42 )
     43 # if params.model_parallel:

File d:\ProgramData\.conda\envs\easyedit\lib\site-packages\torch\serialization.py:791, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    788 if 'encoding' not in pickle_load_args.keys():
    789     pickle_load_args['encoding'] = 'utf-8'
--> 791 with _open_file_like(f, 'rb') as opened_file:
    792     if _is_zipfile(opened_file):
    793         # The zipfile reader is going to advance the current file position.
    794         # If we want to actually tail call to torch.jit.load, we need to
    795         # reset back to the original position.
    796         orig_position = opened_file.tell()

File d:\ProgramData\.conda\envs\easyedit\lib\site-packages\torch\serialization.py:271, in _open_file_like(name_or_buffer, mode)
    269 def _open_file_like(name_or_buffer, mode):
    270     if _is_path(name_or_buffer):
--> 271         return _open_file(name_or_buffer, mode)
    272     else:
    273         if 'w' in mode:

File d:\ProgramData\.conda\envs\easyedit\lib\site-packages\torch\serialization.py:252, in _open_file.__init__(self, name, mode)
    251 def __init__(self, name, mode):
--> 252     super().__init__(open(name, mode))

PermissionError: [Errno 13] Permission denied: './results/models/MEND/gpt2-xl'
```

Here are something that I can offer you:

1. Before this problem occurred, it tipped me that `FileNotFoundError: [Errno 2] No such file or directory: './results/models/MEND/gpt2-xl'`, thus I made this directory manually.
2. I have re-opened VS Code with Administrator privilege, and it still did not work. 
3. I tried to omit the `archive: ./results/models/MEND/gpt2-xl` setting, but the program told me that it must be set.
4. This code was run in a virtual environment `easyedit` (`conda create -n easyedit python=3.9.19`), and the packages are installed according the `requirements.txt`.
5. I ran this code on Windows 11 x 64 bit System.

The content of `gpt2-xl.yaml` is:

``` yaml
# Model

archive: ./results/models/MEND/gpt2-xl
alg_name: "MEND"
device: 0
model_name: ./hugging_cache/openai-community/gpt2-xl

model_class: GPT2LMHeadModel
tokenizer_class: GPT2Tokenizer
tokenizer_name: ./hugging_cache/openai-community/gpt2-xl
model_parallel: false
inner_params:
- transformer.h.45.mlp.c_proj.weight
- transformer.h.45.mlp.c_fc.weight
- transformer.h.46.mlp.c_proj.weight
- transformer.h.46.mlp.c_fc.weight
- transformer.h.47.mlp.c_proj.weight
- transformer.h.47.mlp.c_fc.weight

# Method
alg: MEND
lr: 1e-6
edit_lr: 1e-4
lr_lr: 1e-4
lr_scale: 1.0
seed: 42
cedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null
one_sided: False
n_hidden: 1
hidden_dim: null
init: id
norm: True
combine: True
x_only: False
delta_only: False
act: relu
rank: 1920
mlp_class: IDMLP
shared: True

# Train
batch_size: 1
model_save_pt: 5000
silent: False
#max_epochs: 1
max_iters: 100000
log_interval: 1000
eval_log_interval: 1000
final_eval: True
val_interval: 1000
early_stop_patience: 20000
early_stop_key: "loss/total_edit_val"
eval_only: True
half: False
debug: False
save: False
verbose: True

val_batch_size: 5
accumulate_bs: 10
val_steps: 500 # only for debug
opt: Adam
grad_clip: 100.

# Output

results_dir: ./results
```

What is the parameter `archive` used for ?

Should I configure or download something to the position `./results/models/MEND/gpt2-xl` ?
